#!/usr/bin/env bash
# shellcheck shell=bash
# Install Talisman, with global Git-hook mutation available only by explicit opt-in.

set -o errexit
set -o nounset
set -o pipefail

if [[ -z "${MANTLE_ROOT:-}" ]]; then
	MANTLE_ROOT="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd -P)"
fi
export MANTLE_ROOT

# shellcheck disable=SC1091
source "${MANTLE_ROOT}/lib/install/runtime.sh"

talisman_home="${TALISMAN_HOME:-${XDG_DATA_HOME:-${HOME}/.local/share}/talisman}"
talisman_hooks_directory="${TALISMAN_HOOKS_DIRECTORY:-${XDG_CONFIG_HOME:-${HOME}/.config}/git/hooks}"
talisman_hook_type="${TALISMAN_HOOK_TYPE:-pre-commit}"
configure_global_hook="0"
force_hook="0"
talisman_dry_run="0"
declare -a github_arguments=()

# @description Print mantle install talisman usage.
mantle_install_talisman_usage() {
	printf "%s\n" \
		"Usage: mantle install talisman [COMMON_OPTIONS] [--talisman-home DIRECTORY]" \
		"                        [--configure-global-hook] [--hook-type pre-commit|pre-push|both]" \
		"                        [--hooks-dir DIRECTORY] [--force-hook]" \
		"" \
		"COMMON_OPTIONS: --version, --install-dir, --dry-run, and --no-verify." \
		"Global git configuration is changed only with --configure-global-hook."
}

# @description Write one guarded global Talisman Git hook.
# @arg $1 string Hook name.
mantle_install_talisman_write_hook() {
	local hook_name="${1:-}"
	local hook_path="${talisman_hooks_directory%/}/${hook_name}"

	if (($# != 1)) || [[ "${hook_name}" != "pre-commit" && "${hook_name}" != "pre-push" ]]; then
		return 64
	fi
	if [[ -e "${hook_path}" && "${force_hook}" != "1" ]]; then
		mantle_log_error "Refusing to overwrite an existing hook: ${hook_path}"
		mantle_log_error "Use --force-hook only after reviewing the existing file"
		return 73
	fi
	mkdir -p "${talisman_hooks_directory}"
	{
		printf "#!/usr/bin/env bash\n"
		printf "# Generated by mantle install talisman.\n"
		printf "talisman_command=\"\${TALISMAN_HOME:-%s}/bin/talisman\"\n" "${talisman_home}"
		printf "if [[ ! -x \"\${talisman_command}\" ]]; then\n"
		printf "  printf \"talisman hook skipped: executable unavailable\\n\" >&2\n"
		printf "  exit 0\n"
		printf "fi\n"
		printf "exec \"\${talisman_command}\" --githook %q\n" "${hook_name}"
	} >"${hook_path}"
	chmod 0755 "${hook_path}"
}

while (($# > 0)); do
	case "$1" in
	--talisman-home)
		if (($# < 2)) || [[ -z "${2:-}" ]]; then
			mantle_install_talisman_usage >&2
			exit 64
		fi
		talisman_home="$2"
		shift 2
		;;
	--configure-global-hook)
		configure_global_hook="1"
		shift
		;;
	--hook-type)
		if (($# < 2)); then
			mantle_install_talisman_usage >&2
			exit 64
		fi
		talisman_hook_type="$2"
		shift 2
		;;
	--hooks-dir)
		if (($# < 2)) || [[ -z "${2:-}" ]]; then
			mantle_install_talisman_usage >&2
			exit 64
		fi
		talisman_hooks_directory="$2"
		shift 2
		;;
	--force-hook)
		force_hook="1"
		shift
		;;
	--skip-hook)
		configure_global_hook="0"
		shift
		;;
	--help | -h)
		mantle_install_talisman_usage
		exit 0
		;;
	--version | --install-dir)
		if (($# < 2)); then
			mantle_install_talisman_usage >&2
			exit 64
		fi
		github_arguments+=("$1" "$2")
		shift 2
		;;
	--dry-run | --no-verify)
		github_arguments+=("$1")
		if [[ "$1" == "--dry-run" ]]; then talisman_dry_run="1"; fi
		shift
		;;
	*)
		mantle_log_error "Unknown argument: $1"
		mantle_install_talisman_usage >&2
		exit 64
		;;
	esac
done

case "${talisman_hook_type}" in
pre-commit | pre-push | both) ;;
*)
	mantle_log_error "Unsupported hook type: ${talisman_hook_type}"
	exit 64
	;;
esac

MANTLE_INSTALL_TOOL_NAME="talisman"
MANTLE_INSTALL_GITHUB_OWNER="thoughtworks"
MANTLE_INSTALL_GITHUB_REPOSITORY="talisman"
MANTLE_INSTALL_ASSET_TEMPLATE="talisman_{{platform}}_{{arch}}"
MANTLE_INSTALL_PLATFORM_LINUX="linux"
MANTLE_INSTALL_PLATFORM_DARWIN="darwin"
MANTLE_INSTALL_ARCH_X86_64="amd64"
MANTLE_INSTALL_ARCH_ARM64="arm64"
MANTLE_INSTALL_ARCH_X86="386"
MANTLE_INSTALL_CHECKSUM_ASSET_TEMPLATE="checksums"
MANTLE_INSTALL_ARCHIVE_FORMAT="raw"
MANTLE_INSTALL_BINARY_NAME="talisman"
MANTLE_INSTALL_DIRECTORY="${talisman_home}/bin"
declare -a MANTLE_INSTALL_VERIFY_ARGUMENTS=("--version")

mantle_install_github_main "${github_arguments[@]}"

if [[ "${configure_global_hook}" == "1" && "${talisman_dry_run}" == "0" ]]; then
	if ! mantle_guard_has_command git; then
		mantle_log_error "Configuring global hooks requires git"
		exit 69
	fi
	case "${talisman_hook_type}" in
	pre-commit) mantle_install_talisman_write_hook "pre-commit" ;;
	pre-push) mantle_install_talisman_write_hook "pre-push" ;;
	both)
		mantle_install_talisman_write_hook "pre-commit"
		mantle_install_talisman_write_hook "pre-push"
		;;
	esac
	git config --global core.hooksPath "${talisman_hooks_directory}"
	mantle_log_success "Configured Talisman global hooks in ${talisman_hooks_directory}"
fi
