// Generated by egohygiene/identity. Do not edit.
export type IdentityTokenPath = "color.action.primary" | "color.brand.human" | "color.brand.primary" | "color.brand.secondary" | "color.canvas" | "color.terminal.canvas" | "color.terminal.text" | "color.text" | "motion.duration.reduced" | "motion.duration.standard" | "typography.body.family";
export declare const tokens: Readonly<Record<IdentityTokenPath, unknown>>;
export default tokens;
